### ISSUE TITLE
Call Back Issue

### ISSUE THREAD

**Issue by sanzcarlos** [bdm1981/finesseGadgets#13]
Hello:

In Spain and others countries, the access codes is 0, in the function makeCall, the variable number is an integer and if the first digits is 0, this digits are remove and the call is not working. Thanks

Reagrds.
Carlos Sanz

**Comment by Ollie1938** [comment]
Hi, 
I am experiencing the same problem. 
Did you find a solution to this problem? 
Thanks
Oliver

**Comment by bdm1981** [comment]
Hi @Ollie1938 , 

On line 318 of callHistoryGadget.js put single quotes around **" + num + "**  It should look like the line below.

`
historyTable += "<tr><td>"+ calls[i].date.toLocaleTimeString() +"</td><td>" + calls[i].direction +"</td><td>"+ calls[i].duration +"</td><td>"+ calls[i].number +"</td><td>"+ detail +"</td><td><button onClick=\"finesse.modules.callHistoryGadget.makeCall('" + num + "')\">Call Back</button></td></tr>";
`

Once you have had a chance to test, let me know the outcome. I will update the code once confirmed.
- Brad

**Comment by Ollie1938** [comment]
Hi Brad, 
Thanks for getting back to me so quickly. 
That worked perfectly. 
Thank you very much :)
Regards
Oliver
