### ISSUE TITLE
Inbound Call "Browser Pop up" Error

### ISSUE THREAD

**Issue by sbaird1224** [bdm1981/finesseGadgets#14]
Hi,

I was able to install this gadget with instructions you provided and it looks and works great.  I notice when inbound call comes into agent a new browser window opens and produces the following HTTP 404 error.  The Finesse window with the gadget continues to work fine with no issues, its just this second browser window that opens during inbound call.  Same behavior and error message using both Firefox and IE.  Has anyone else run across this issue?

HTTP Status 404 - /desktop/container/$%7Buserlink%7D 

 type: Status report

message: /desktop/container/$%7Buserlink%7D

description: The requested resource is not available. 

Thank you,
Scott

**Comment by bdm1981** [comment]
I have never run into this before. Are you sure it i coming from the call history gadget? Send me a copy of your xml & js files and I can take a look.

**Comment by sbaird1224** [comment]
Hi Brad,

Thanks for replying back and looking at this for me.  Attached is my xml
and js files you requested.

Thanks,
Scott

**Comment by bdm1981** [comment]
Unfortunately, those didn't attach. Can you send them directly to me: bdm@bdmcomputers.com

**Comment by sbaird1224** [comment]
Issue Resolved: First and foremost, there was no issue with the CallHistory Gadget.   I found out one of my Finesse screenpop workflows was set to all incoming calls and no conditions were added.  This caused a blank screenpop for every inbound call that arrived.  Once the condition was corrected the screenpop was no long appearing.
