### ISSUE TITLE
Using multiple access Codes

### ISSUE THREAD

**Issue by sbaird1224** [bdm1981/finesseGadgets#15]
Hi,

Is there a way to add additional access Codes to the "callHistoryConfig.js for when the callback feature is used.  For example a local outbound call using access code 9 will be different than an international call which uses 9011. 

"accessCode": "9" // access Code

Thanks,
Scott

**Comment by bdm1981** [comment]
Hi Scott,

I can add support for a national and international access code. I will send you a note once I have added this.

**Comment by sbaird1224** [comment]
Great thank you, and if I wanted to NULL the access code all together can I just remove the 9.  for example: "access Code": "" //access code

**Comment by T2Bowen** [comment]
Hi Brad, 

I noticed that in your code you only take US numbers and Access codes into validation. I had to make some changes to the recordCall and how we validate the number for MakeCall to make it work with Swedish number format.
(open numbering plan with numberlength between 5 and 10 digits for external calls)
So far i have only commented those lines in the code to make it work, but will look into some intelligent formatting of the numbers like you have for US-numbers.

**Comment by cptmellow** [comment]
Hi,

I have been having the same issue with callback for international numbers, could you please shed some light on how to differentiate between those two?

Thanks

**Comment by bdm1981** [comment]
@cptmellow Currently all of the number matching is based on a US dial plan. My guess is the access code isn't be added properly based on your number length. You change this behavior by updating the code at line 290 of the CallHistoryGadget.js file. The code looks like this:
``` JavaScript		
// Prepend Access Code on 11 digit numbers
var num = calls[i].number;
if (num.length == 11){
    num = accessCode+num;
}
```

**Comment by cptmellow** [comment]
@bdm1981 Thanks Brad. Do you know if any functionality has changed from 10.5 to 11.5?

**Comment by bdm1981** [comment]
@cptmellow the call history gadget works the same way in 10.5 and 11.5.

**Comment by shoogagoo** [comment]
@bdm1981 Great gadget that you've built. I had to do some modifications to it as well in order to use it for for our international user base, so I ended up replacing the length with a bit of code that just recognizes if the callback number already has three zeros (or 900 for the UK) or not.
The only issue I have now is that elsewhere in Europe we use zero for the outside line but in the UK they use 9 and I haven't figured out how to overcome this issue with two different access codes.

Probably for us a workable solution would be to have two additional lines in the "callHistoryConfig.js" file. One where we could define extension ranges and the second one to indicate which access code to use for those.
Adding something like this could be useful for other users as well.
Do you think this could be something you could add to a future version?

**Comment by bdm1981** [comment]
@shoogagoo What determines if a 9 or 0 should be used? Do the numbers have a unique prefix or length?

**Comment by shoogagoo** [comment]
@bdm1981 We determine the usage of 9 or 0 based upon the agent extension.
We use a 6 digit agent extension and this is unique for each location (i.e one location uses 150000-150999, another uses 151000-151999, etc.).

**Comment by sbaird1224** [comment]
Let me try to clear up what we would like to see in this awesome plug in.  We need to dial out from the U.S. to several different countries with country code and national phone format differences.   For example from the U.S. we need to dial 1+ area code + national phone format (this works fine).  For International dialing we need to dial 011 + country code + national phone number format.  It would be ideal for the agent to just click the call back button and the code can tell how to dial the number regardless of Domestic or International dialing plan.

As you notice in a few examples below the International Australia has 2 digit country code vs. Aruba having 3 digit country code.  Also the two phone numbers have different number length in the national phone number format.  The system will need to except the country code and number length differences for each country.

Examples: 
U.S.: 1+412+555+5555 
International Australia: 011 61 55 4444 333 22
International Aruba: 011 297 55 4444

**Comment by bdm1981** [comment]
@sbaird1224 

Thanks for the clarification. Hopefully I can take a crack at implementing this over the next couple weeks. Once I have something to test I will let you know.

**Comment by bdm1981** [comment]
Since Finesse 11.6 now has a native call history gadget with a callback option, I will not be tackling this.
