### ISSUE TITLE
Missing Time/Duration of calls in CallHistoryGadget

### ISSUE THREAD

**Issue by T2Bowen** [bdm1981/finesseGadgets#16]
Installed this gadget today on a UCCX 11.0.1 and was not able to upload the "finesse-10.5.1.js" file to 3rdpartygadget/files.
I looked at other SampleGadgets from Cisco and found a way to change the information in the "callHistoryGadget.xml" to the following:
            <script type="text/javascript" src="/desktop/assets/js/jquery.min.js"></script>

```
        <!-- Finesse Library -->
        <script type="text/javascript" src="/desktop/assets/js/finesse.js"></script>
```

I have the gadget visible and after a few tries it started to log calls.
I have each call being logged with Number and Inbound/Outbound but the Time and Duration are not shown.
For example a line could look like this:
[Time] [Type] [Duration] [Number] [Detail]
NaN Inbound 00:00:NaN +46104999400+46104999400 

I have tried to follow the code but do you have any tip on what can be wrong or where to look in the code for the Time/Duration information?
I guess the information that the Gadget is requesting from the Finesse is not as expected or the request itself needs to be tweaked.

I also have problem that nothing happens when i click on the "Call Back" to initiate a call. No error or anything. 

I can not see any error-message in the Finesse-client log-file for any of the two problems.
Any clues from your side ?

**Comment by bdm1981** [comment]
I have seen this before with IE and compatibility mode. Are you running in compatibility mode by chance?

**Comment by T2Bowen** [comment]
Thanks. After changing the Compability mode in IE i got time, duration and call back to work as expected.

**Comment by bdm1981** [comment]
Great!

**Comment by dj2212** [comment]
Can it be made to work in compatibility mode as well?

**Comment by bdm1981** [comment]
I can look into making it work in compatibility mode. Do you have other
gadgets that require that? I am traveling this week and will dig into it
early next week.

## 

Brad McAllister
CCIE #40627
bdm@bdmcomputers.com
