### ISSUE TITLE
Finesse call Histroy

### ISSUE THREAD

**Issue by bryantg9** [bdm1981/finesseGadgets#17]
Hi

The call History is blank on my gadget..any assistance would be appreciated

thanks

**Comment by bryantg9** [comment]
resolved.. 

in 10.6 you have to change the XML to use the below instead of the 10.5



```
        <script type="text/javascript" src="/desktop/assets/js/jquery.min.js"></script>

        <!-- Finesse Library -->
        <script type="text/javascript" src="/desktop/assets/js/finesse.js"></script>
```

**Comment by bdm1981** [comment]
Thanks, I will update to include an XML per/version so others don't run into the same issue.
