### ISSUE TITLE
New call arrival is not taking Sort order into account when adding it to Call History

### ISSUE THREAD

**Issue by T2Bowen** [bdm1981/finesseGadgets#19]
Small problem with latest version of gadget. When sorting with the oldest call at the bottom and earliest at the top i still get new calls at the end of the CallHistory.
Sorting by clicking on header does not work as expected after this. I guess the sort-mechanism in the code does not take the sort-order into account when a new call arrives in the history and put this call on the top of the list.

Logout of Finesse and logging back in fixes the Call History order

**Comment by bdm1981** [comment]
Yes, the code current doesn't remember changes to the sort order. I am working on an update that not only remembers the sort order but will add a visual indicator to the header that is currently used for sorting.

**Comment by bdm1981** [comment]
The latest commit should resolve this. This turned into a much bigger update than I had expected. Please let me know ASAP if I inadvertently broke anything else. I tested thoroughly on my side but could have missed something.

**Comment by bdm1981** [comment]
After doing more testing today. I found the changes made over the weekend affected how the call history was saved to the local storage. Everything works fine until you refresh your browser. I will release a fix ASAP.

**Comment by bdm1981** [comment]
@TDC-bowen - just pushed a new version that fixed the bug I introduced with the sorting. Please let me know when you have a moment to test it.

**Comment by T2Bowen** [comment]
Hi Brad, I have updated our lab-system and the sorting seems to work as expected now. I will update our customers UCCX during the following days and report any issues for sure. 
(I have to change the number validation from US to Swedish numbering plan in the "callHistoryGadget.js"-file, but this is a small issue)
Thanks for your work on this gadget !

**Comment by bdm1981** [comment]
Glad to hear it. Can you share the Swedish number plan info? That might be helpful for others. I can add it in the code and comment it out by default.
