### ISSUE TITLE
Error in SMS Gadget

### ISSUE THREAD

**Issue by villarrealed** [bdm1981/finesseGadgets#20]
I'm seeing the following error in the gadget after sending an SMS message.  I'm not sure if this is related to the Firebase request or the Tropo request.

"Missing or malformed url parameter"

**Comment by bdm1981** [comment]
Thanks for contacting me about this. I was just looking into this for someone else. It appears to be an issue with changes made with the latest firebase 3.x updates. I am going to refactor my code to account for these changes and will post and update shortly.

**Comment by bdm1981** [comment]
I updated the code to support firebase 3.x. Please download the latest code and follow the updated instructions.
