### ISSUE TITLE
Call can not be completed as dialed

### ISSUE THREAD

**Issue by broeben** [bdm1981/finesseGadgets#21]
I have uploaded the script.  Changed the appropriate entries in the callHistoryConfig.js to have access code 9, to get an outside line.   Updated reasonID and callDetail variables as well.

The gadget works correct on logging inbound and outbound calls.  But when I press the CallBack button, the phone says "Call cannot be completed as dialed".   This would usually happen if it was trying to dial the number without the access code.   Can you assist?  What am I missing?

**Comment by bdm1981** [comment]
Can you confirm that the agent can make an outbound call to the same number by dialing from the call control gadget native to Finesse?

**Comment by broeben** [comment]
Yes, I have confirmed that I can make an outbound call to the same number if I use the native call control gadget in Finesse.

**Comment by bdm1981** [comment]
Is there anything wrong with the format of the number as it is displayed in the call history? All the callback button does is prepend that number with the access code. In your case this would be a 9. When you dialed from the call control gadget did you include the 9? I have some customers that prepend the 9 via CUCM. In this case you don't need to provide the access code in the call history gadget.

**Comment by broeben** [comment]
That answered my question.  I was testing the callback incorrectly.   If I picked up the phone and dialed out to the outside line, it would show in the call history.   So when I hit Call Back, it was dialing 9 twice.   I then tested by using Call Back on a # I received inbound from the ACD.   The call back worked.   You can close the issue.
