### ISSUE TITLE
Last call are not updated until page is refreshed or sort order changed

### ISSUE THREAD

**Issue by T2Bowen** [bdm1981/finesseGadgets#22]
Last call are not updated until page is refreshed or sort order changed.
This seems to happen both on incoming and outgoing calls on the last version of the callHistoryGadget.
is this a limitation or can it be fixed ?

**Comment by azmcmillan** [comment]
I'm having the same behavior on a fresh 11.0 CCX install using the latest version of the callHistoryGadget (downloaded 11/17).

Also the callHistoryGadget isn't loading in IE 11.0.9600.18097, only showing up in Firefox 50.0.

**Comment by bdm1981** [comment]
Thanks for the bringing this to my attention. I think I found the issue. Just need to do some more testing. Will send an update soon.

**Comment by bdm1981** [comment]
just committed the fix.

**Comment by T2Bowen** [comment]
implemented and verified !
thanks Brad !

**Comment by michalkaska99** [comment]
Can I please ask, what was the issue and how was i fixed?

**Comment by bdm1981** [comment]
When I added the ability for sorting to be persistent, it introduced a bug in how the calls were recorded. The latest committed code fixes this issue.

**Comment by michalkaska99** [comment]
OK, thanks, but I made some customization of this script, so it would help me to know, which part of code is affected. Otherwise I will have to analyze it manually.

Michal



Tel: +420 604 216 428
Jabber: michal.kaska@simac.cz
