### ISSUE TITLE
Not Working right

### ISSUE THREAD

**Issue by ponwude** [bdm1981/finesseGadgets#23]
Hi,

This gadget load ok but I do not see any call history after making /Receiving several calls. 

UCCX 10.6

**Comment by bdm1981** [comment]
Sorry to hear that. Can you provide the following:

- What browser are you using?
- Is the gadget installed on the UCCX system or an external web server?
- When the gadget loads do you see inbound and outbound under call type with the total of 0 next to each?
![image](https://cloud.githubusercontent.com/assets/10137511/20872065/3258a256-ba61-11e6-98cd-c4916596960d.png)

**Comment by ponwude** [comment]
Hi,

Browser is IE v11
Gadget is installed on the UCCX System
No I do not see the inbound and outbound. Only the headers are shown (the part in blue)

**Comment by bdm1981** [comment]
This usually means that one of the JavaScript libraries is not loading properly. Did you upload all of the JS files that are included in this repo to the UCCX server? If all of the files were added to UCCX, you shouldn't need to make any adjustments to the file paths in the callHistoryGadget.xml file.  

If that all looks good and its still not working, UCCX 10.6.1 started making the finesse JS libraries centrally available for gadgets to use.  To reference these, update the path for finesse and jquery in the callHistoryGadget.xml file to point to the following:
`<script type="text/javascript" src="/desktop/assets/js/jquery.min.js"></script>`
`<script type="text/javascript" src="/desktop/assets/js/finesse.js"></script>`

**Comment by ponwude** [comment]
I actually updated the path for finesse and jquery prior to posting this. Did not change anything.

Confirm that I don't have to restart Finesse tomcat.

**Comment by ponwude** [comment]
Fixed it.

There was an issue with this line 

"callDetail": “callVariable6” // Call Variable to place in the Detail field

The wrong quotes.

**Comment by bdm1981** [comment]
Glad you got it working!
