### ISSUE TITLE
incorrect call type

### ISSUE THREAD

**Issue by michalkaska99** [bdm1981/finesseGadgets#24]
Hallo,
I have recognized an issue for calls from logged-in agent to logged-in agent. In this call scenarion on called agent is call presented as outgoing andf not as incoming
When calling agents log-out form finesse, that call type is presented corectly as incoming.

**Comment by bdm1981** [comment]
@michalkaska99 Is this agent to agent call displaying as an incoming call for both agents involved in the call? Can you provide the type and version of CC? CCX or CCE and Version.

Thanks

**Comment by michalkaska99** [comment]
Hallo,

I tested it on CCX version 10.5 and also ccx 11.5. Same bahavior.

Scenarios
Agent to agent, direct call = called agent registers Outbound call, instead of inbound

When calling agent gets logout, and than call to agent, call type is OK.

When I debug the script and output „trackDialog[i].type“ to console, I see, that here it is frong, so maybe, it is issue in finesse.js library.

Michal







Tel: +420 604 216 428
Jabber: michal.kaska@simac.cz

**Comment by bdm1981** [comment]
@michalkaska99 I finally got a chance to dig into this. I just committed an update that should resolve this.
