### ISSUE TITLE
History Blank

### ISSUE THREAD

**Issue by merb5611** [bdm1981/finesseGadgets#26]
Hi Brad,

Like some others I'm not seeing any data in the History gadget.  Running UCCX 10.6 (clustered Pub/Sub if this matters), trying on IE 11.  Gadget loads as expected just no data.

Tried updating the finesse and jquery sections of callHistoryGadget.xml as you and others have specified prior, then relaunched the browser with the ?nocache to reload the gadget.  I'll attach the client logs if this helps at all...nothing is really jumping out at me in the logs, appears that the gadget is detecting the call.

Thanks for any assistance you can provide!
-Mitch

[client logs.txt](https://github.com/bdm1981/finesseGadgets/files/720113/client.logs.txt)

**Comment by bdm1981** [comment]
@merb5611,

This usually occurs when jQuery doesn't load properly. As of UCCX 10.6 the jQuery and finesse libraries are provided on the finesse server. I just updated the callHistoryGadget.xml file to include examples of the file paths for the various versions and deployment methods. I also updated the installation instructions and troubleshooting section with a screenshot of what the gadget should look like when everything loads properly along with a screenshot of when jQuery didn't load. 

Take a look at these updates and see if it resolves your issue. Also, try Firefox just to rule out IE as a culprit. 

- Brad

**Comment by merb5611** [comment]
Thanks, I got it working in our lab using FF and UCCX 10.6...I will have a colleague test at the customer site today.

**Comment by merb5611** [comment]
FF does work onsite, seems like IE is defaulting to IE 8 Mode when launching instead of 11...so they'll track that down.  Thanks for streamlining the install process.  You can close this inquiry.

**Comment by bdm1981** [comment]
@merb5611 Thanks for the follow-up. I ran into a customer where their Group Policy settings were forcing IE into compatibility mode. Might be something to check into if the IE client doesn't specifically show the domain in the compatibility list.

- Brad
