### ISSUE TITLE
Incoming Consult calls are presented as Outgoing in callHistory Gadget 

### ISSUE THREAD

**Issue by T2Bowen** [bdm1981/finesseGadgets#28]
Customer are having problems with some Consult Transfer calls ending up as two entries in the callHistory gadget. 
One entry as an "Outgoing call" and one entry as the incoming call (external part that was transfered).
I have problems to recreate the problem and test the latest version in lab so i am creating this here for if there is something that needs to be fixed.

The Agent "suswik" has the DN 62297 and are taking UCCX-calls on a script that has CTI-RP with DN=69856.
It seems that at least some calls that are redirected from another script (with DN 61099) to this CTI-RP could be part of this error.
From my understanding the caller "0703153567" did call the 61099 CTI-RP and that call was then forwarded (Consult transfer) to the Application that this agent was part of.

I am including the screenshot and FinessClient-log for reference:
[callHistoryConsultTransfer.zip](https://github.com/bdm1981/finesseGadgets/files/890292/callHistoryConsultTransfer.zip)

The gadget is running on a UCCX 10.6-server.
Regards
Mikael Hansson

**Comment by bdm1981** [comment]
I was able to reproduce this. The logs were showing the DN=63047 was doing a consult transfer to 69856 and staying on the line until the agent picked up the call. Once the agent picked up the transfer to was made. This  breaks the logic for the call history script. Update the case statement for the consult calls in the  callHistoryGadget.js file to match the code below.
```JavaScript
case "CONSULT":
  if (dialog.getToAddress() == user.getExtension()){
    number = dialog.getFromAddress();
    direction.desc = "Consult From";
    direction.dir = "in";
  }else if(dialog.getFromAddress() == user.getExtension()){
    number = dialog.getToAddress();
    direction.desc = "Consult To";
    direction.dir = "out";
  }else if(dialog.getToAddress() != user.getExtension()){
    number = dialog.getToAddress();
    direction.desc = "Consult From";
    direction.dir = "in";
  }
break;
```

Once you have confirmed this resolved the issue I will update the repo.

Sorry it took me a while to get time to look into this.

- Brad
