### ISSUE TITLE
The Log message is not useful.

### ISSUE THREAD

**Issue by fraser125** [bdm1981/finesseGadgets#35]
https://github.com/CiscoSE/finesseGadgets/blob/1958bd6e4488673d1e73c82944a80bbb4d08ace5/callHistoryGadget/11.x/callHistoryGadget.js#L60

I was reviewing my logs and found this: 
time sort: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

I suggest that this log message doesn't provide any real value to anyone. 
Please consider removing this line.

**Comment by bdm1981** [comment]
Hi @fraser125 ,

Thanks for checking out this project. I am out at Cisco Live this week but will clean up the log statements when I return. 

- Brad

**Comment by cmlccie** [comment]
@bdm1981 , I like that log message!! 🤣

**Comment by bdm1981** [comment]
@fraser125 - I removed that log statement and committed an update.
