### ISSUE TITLE
Gadget Rendering

### ISSUE THREAD

**Issue by rescueteam53** [bdm1981/finesseGadgets#36]
I received the error below in finesse. Any clue what I may have done wrong?
 
There were issues rendering this gadget.
org.apache.shindig.common.xml.XmlException: The processing instruction target matching "[xX][mM][lL]" is not allowed. At: (13,6)

http://localhost:8082/3rdpartygadget/files/callHistoryGadget/callHistoryGadget.xml

**Comment by bdm1981** [comment]
@rescueteam53 

I haven't seen that error before. It seems like the xml file might have been altered. Can you post the xml file here or share it with me via webex teams? bmcallis@cisco.com

**Comment by rescueteam53** [comment]
Thanks for your response. I'll share via webex teams

**Comment by bdm1981** [comment]
It looks like this issue was caused by the comment block I added at the top of the XML file for the cisco sample code license. I moved this inside the XML tag. The gadget should now render properly. 
Sorry about that.
